query DistributionRuleQuery($uuid: String!) {
  distributionRule (uuid: $uuid) {
    _id
    uuid
    name
    status
    statusChangedAt
    createdAt
    updatedAt
    latestMigration {
      startDate
    }
    executionType
    totalMigratedClients
  }
}
