query IpWhitelistQuery($args: IpWhitelistSearch__Input) {
  ipWhitelistSearch(args:$args) {
    content {
      uuid
      ip
      createdAt
      description
    }
    page
    number
    totalElements
    size
    last
  }
}
