mutation CreateDeskMutation(
  $name: String!
  $deskType: Desk__Types__Enum!
  $officeUuid: String!
  $language: String!
) {
  hierarchy {
    createDesk (
      name: $name
      deskType: $deskType
      officeId: $officeUuid
      language: $language
    )
  }
}
