import I18n from '../../../../../../../../../../utils/fake-i18n';

const attributeLabels = {
  lifeTime: I18n.t('BONUS_CAMPAIGNS.REWARDS.LIFE_TIME'),
  multiplier: I18n.t('BONUS_CAMPAIGNS.REWARDS.MULTIPLIER'),
  multipliersType: I18n.t('BONUS_CAMPAIGNS.REWARDS.MULTIPLIERS_TYPE'),

  grant: I18n.t('BONUS_CAMPAIGNS.REWARDS.GRANT'),
  name: I18n.t('BONUS_CAMPAIGNS.REWARDS.NAME'),
  providerId: I18n.t('BONUS_CAMPAIGNS.REWARDS.PROVIDER'),
  gameId: I18n.t('BONUS_CAMPAIGNS.REWARDS.GAMES'),

  numberOfCoins: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.NUMBER_OF_COINS'),
  coinSize: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.COIN_SIZE'),
  betLevel: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.BET_LEVEL'),
  coinValueLevel: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.COIN_VALUE_LEVEL'),

  freeSpins: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.FREE_SPINS'),
  freeSpinReward: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.FREE_SPIN_REWARD'),
  betPerLine: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.BET_PER_LINE'),
  template: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.TEMPLATE'),
  prize: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.PRIZE'),
  wagering: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.WAGERING'),
  capping: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.CAPPING'),
  moneyPriority: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.MONEY_PRIORITY'),
  spinValue: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.SPIN_VALUE'),
  totalValue: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.TOTAL_VALUE'),
};

const attributePlaceholders = {
  days: I18n.t('BONUS_CAMPAIGNS.REWARDS.PLACEHOLDERS.DAYS'),
  notSet: I18n.t('BONUS_CAMPAIGNS.REWARDS.PLACEHOLDERS.NOT_SET'),
};

export {
  attributeLabels,
  attributePlaceholders,
};

