query ClientsAmountQuery(
  $salesStatuses: [String]!
  $countries: [String]!
  $languages: [String]!
  $sourceBrand: String!
  $firstTimeDeposit: Boolean
  $registrationPeriodInHours: Int
  $registrationDateRange: DistributionRule__DateRange__Input
  $lastNotePeriodInHours: Int
  $lastNoteDateRange: DistributionRule__DateRange__Input
  $timeInCurrentStatusInHours: Int
  $affiliateUuids: [String]
  $desks: [String]
  $teams: [String]
) {
  distributionRuleClientsAmount(
    salesStatuses: $salesStatuses
    countries: $countries
    languages: $languages
    sourceBrand: $sourceBrand
    firstTimeDeposit: $firstTimeDeposit
    registrationPeriodInHours: $registrationPeriodInHours
    registrationDateRange: $registrationDateRange
    lastNotePeriodInHours: $lastNotePeriodInHours
    lastNoteDateRange: $lastNoteDateRange
    timeInCurrentStatusInHours: $timeInCurrentStatusInHours
    affiliateUuids: $affiliateUuids
    desks: $desks
    teams: $teams
  )
}
