import I18n from '../../../../../../../../utils/fake-i18n';

const attributeLabels = {
  searchBy: I18n.t('CONSTANTS.BONUS_CAMPAIGNS.FILTER_FORM.ATTRIBUTES_LABELS.SEARCH_BY'),
  bonusType: I18n.t('CONSTANTS.BONUS_CAMPAIGNS.FILTER_FORM.ATTRIBUTES_LABELS.BONUS_TYPE'),
  availabilityDateRange: I18n.t('CONSTANTS.BONUS_CAMPAIGNS.FILTER_FORM.ATTRIBUTES_LABELS.AVAILABILITY_DATE_RANGE'),
  startDate: I18n.t('CONSTANTS.BONUS_CAMPAIGNS.FILTER_FORM.ATTRIBUTES_LABELS.START_DATE'),
  endDate: I18n.t('CONSTANTS.BONUS_CAMPAIGNS.FILTER_FORM.ATTRIBUTES_LABELS.END_DATE'),
};
const attributePlaceholders = {
  searchBy: I18n.t('CONSTANTS.BONUS_CAMPAIGNS.FILTER_FORM.ATTRIBUTES_PLACEHOLDERS.SEARCH_BY'),
};

export {
  attributeLabels,
  attributePlaceholders,
};
