query NotificationQuery($args: NotificationCenterSearch__Input) {
  notificationCenter(args: $args) @connection(key: "NotificationCenterPopup") {
    content {
      read
      uuid
      priority
      client {
        uuid
        firstName
        lastName
        languageCode
      }
      createdAt
      type
      subtype
      details
    }
    last
    size
    number
    totalElements
  }
}
