mutation UpdatePaymentSystemMutation(
  $paymentId: String!,
  $paymentSystem: String!,
) {
  payment {
    changePaymentSystem (
      paymentId: $paymentId,
      paymentSystem: $paymentSystem,
    )
  }
}
