query SymbolQuery($symbolName: String!) {
  tradingEngine {
    symbol(symbolName: $symbolName) {
      symbolType
      digits
      quoteCurrency
      baseCurrency
      filtration {
        discardFiltrationLevel
        filterSmoothing
        hardFilter
        hardFiltrationLevel
        softFilter
        softFiltrationLevel
      }
      symbolSessions {
        dayOfWeek
        quote {
          openTime
          closeTime
        }
        trade {
          openTime
          closeTime
        }
      }
    }
  }
}
