export const attributeLabels = {
  department: 'OPERATORS.PROFILE.DEPARTMENTS.LABELS.DEPARTMENT',
  role: 'OPERATORS.PROFILE.DEPARTMENTS.LABELS.ROLE',
  firstName: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.FIRST_NAME',
  lastName: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.LAST_NAME',
  country: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.COUNTRY',
  phoneNumber: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.PHONE',
  sip: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.SIP',
  email: 'COMMON.EMAIL',
  whiteListedIps: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.WHITE_LISTED_IP',
  restrictedCountries: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.RESTRICTED_COUNTRIES',
};
