const attributeLabels = {
  department: 'OPERATORS.PROFILE.DEPARTMENTS.LABELS.DEPARTMENT',
  role: 'OPERATORS.PROFILE.DEPARTMENTS.LABELS.ROLE',
};

const personalFormAttributeLabels = {
  firstName: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.FIRST_NAME',
  lastName: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.LAST_NAME',
  country: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.COUNTRY',
  phoneNumber: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.PHONE',
  email: 'COMMON.EMAIL',
  whiteListedIps: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.WHITE_LISTED_IP',
  restrictedCountries: 'OPERATORS.PROFILE.PERSONAL_FORM.LABELS.RESTRICTED_COUNTRIES',
};

export {
  attributeLabels,
  personalFormAttributeLabels,
};

export default attributeLabels;
