query FilesByProfileUuidQuery($clientUuid: String!){
  clientFiles(
    clientUuid: $clientUuid,
  ) {
    verificationType
    attemptsLeft
    documents {
      documentType
      verificationTime
      verifiedBy
      verificationStatus
      files {
        _id
        clientUuid
        client {
          fullName
        }
        fileName
        title
        documentType
        mediaType
        status
        uploadBy
        uuid
        verificationType
        type
        uploadDate
        expirationDate
        note {
          _id
          noteId
          targetUUID
          targetType
          playerUUID
          subject
          content
          pinned
          changedAt
          changedBy
          operator {
            fullName
          }
        }
      }
    }
  }
}
