export default {
  firstName: 'LEAD_PROFILE.PROMOTE_MODAL.LABELS.FIRST_NAME',
  lastName: 'LEAD_PROFILE.PROMOTE_MODAL.LABELS.LAST_NAME',
  email: 'LEAD_PROFILE.PROMOTE_MODAL.LABELS.EMAIL',
  country: 'LEAD_PROFILE.PROMOTE_MODAL.LABELS.COUNTRY',
  currency: 'LEAD_PROFILE.PROMOTE_MODAL.LABELS.CURRENCY',
  password: 'LEAD_PROFILE.PROMOTE_MODAL.LABELS.PASSWORD',
  language: 'LEAD_PROFILE.PROMOTE_MODAL.LABELS.LANGUAGE',
  salesRepresentative: 'LEAD_PROFILE.PROMOTE_MODAL.LABELS.SALES_REP',
  salesDesk: 'LEAD_PROFILE.PROMOTE_MODAL.LABELS.SALES_DESK',
};
