import I18n from '../../utils/fake-i18n';

export default {
  firstName: I18n.t('LEAD_PROFILE.PROMOTE_MODAL.LABELS.FIRST_NAME'),
  lastName: I18n.t('LEAD_PROFILE.PROMOTE_MODAL.LABELS.LAST_NAME'),
  email: I18n.t('LEAD_PROFILE.PROMOTE_MODAL.LABELS.EMAIL'),
  country: I18n.t('LEAD_PROFILE.PROMOTE_MODAL.LABELS.COUNTRY'),
  currency: I18n.t('LEAD_PROFILE.PROMOTE_MODAL.LABELS.CURRENCY'),
  password: I18n.t('LEAD_PROFILE.PROMOTE_MODAL.LABELS.PASSWORD'),
  language: I18n.t('LEAD_PROFILE.PROMOTE_MODAL.LABELS.LANGUAGE'),
  salesRepresentative: I18n.t('LEAD_PROFILE.PROMOTE_MODAL.LABELS.SALES_REP'),
  salesDesk: I18n.t('LEAD_PROFILE.PROMOTE_MODAL.LABELS.SALES_DESK'),
};
