mutation UpdateClientAddressMutation(
  $playerUUID: String!
  $countryCode: String
  $city: String
  $state: String
  $postCode: String
  $poBox: String
  $address: String
) {
  profile {
    updateAddress(
      playerUUID: $playerUUID
      countryCode: $countryCode
      city: $city
      state: $state
      postCode: $postCode
      poBox: $poBox
      address: $address
    ) {
      _id
      address {
        address
        city
        countryCode
        poBox
        postCode
        state
      }
    }
  }
}
