mutation UpdateDistributionRuleMutation(
  $uuid: String!
  $ruleName: String
  $ruleOrder: Int
) {
  distributionRule {
    update(
      uuid: $uuid
      ruleName: $ruleName
      ruleOrder: $ruleOrder
    ) {
      _id
      name
      order
    }
  }
}
