mutation AsteriskCreateCallMutation(
  $uuid: String!
  $phoneType: Click2CallPhone__Type__Enum!
  $customerType: Click2CallCustomer__Type__Enum!
  $prefix: String!
) {
  clickToCall {
    asterisk {
      createCall(
        uuid: $uuid
        phoneType: $phoneType
        customerType: $customerType
        prefix: $prefix
      )
    }
  }
}

