mutation SquaretalkCreateCallMutation(
  $uuid: String!
  $phoneType: ClickToCall__Phone__Type__Enum!
  $customerType: ClickToCall__Customer__Type__Enum!
) {
  clickToCall {
    squaretalk {
      createCall(
        uuid: $uuid
        phoneType: $phoneType
        customerType: $customerType
      )
    }
  }
}
