mutation AddBranchManagerMutation(
  $branchUuid: String!,
  $operatorUuid: String!
) {
  hierarchy {
    addBranchManager(
      branchUuid: $branchUuid,
      operatorUuid: $operatorUuid
    )
  }
}
