mutation UpdatePaymentStatusMutation(
  $paymentId: String!,
  $paymentStatus: String,
) {
  payment {
    changePaymentStatus (
      paymentId: $paymentId,
      paymentStatus: $paymentStatus,
    )
  }
}
