query PinnedNotesQuery(
  $targetUUID: String!
  $pinned: Boolean
  $size: Int
) @connection(key: "PinnedNotes") {
  notes(
    targetUUID: $targetUUID
    pinned: $pinned
    size: $size
  ) {
    size
    page
    totalElements
    totalPages
    number
    last
    content {
      _id
      noteId
      targetUUID
      targetType
      playerUUID
      subject
      content
      pinned
      changedAt
      changedBy
      operator {
        fullName
      }
    }
  }
}
