export const attributeLabels = {
  searchBy: 'TRADING_ENGINE.OPERATOR_PROFILE.FEED.FILTER_FORM.SEARCH_BY',
  actionType: 'TRADING_ENGINE.OPERATOR_PROFILE.FEED.FILTER_FORM.ACTION_TYPE',
  creationDateRange: 'TRADING_ENGINE.OPERATOR_PROFILE.FEED.FILTER_FORM.ACTION_DATE_RANGE',
};
