import keyMirror from 'keymirror';
import I18n from '../../../../../../../utils/fake-i18n';

const actions = keyMirror({
  UPLOAD_PLAYERS: null,
  RESET_PLAYERS: null,
  SOFT_RESET_PLAYERS: null,
});

const actionsLabels = {
  [actions.UPLOAD_PLAYERS]: I18n.t('BONUS_CAMPAIGNS.UPLOAD_PLAYERS.NOTIFICATION.ADD_PLAYER'),
  [actions.RESET_PLAYERS]: I18n.t('BONUS_CAMPAIGNS.UPLOAD_PLAYERS.NOTIFICATION.RESET_PLAYER'),
  [actions.SOFT_RESET_PLAYERS]: I18n.t('BONUS_CAMPAIGNS.UPLOAD_PLAYERS.NOTIFICATION.SOFT_RESET_PLAYER'),
};

const actionDescription = {
  [actions.UPLOAD_PLAYERS]: I18n.t('BONUS_CAMPAIGNS.UPLOAD_PLAYERS.MODAL.DESCRIPTION.ADD_PLAYER'),
  [actions.RESET_PLAYERS]: I18n.t('BONUS_CAMPAIGNS.UPLOAD_PLAYERS.MODAL.DESCRIPTION.RESET_PLAYER'),
  [actions.SOFT_RESET_PLAYERS]: I18n.t('BONUS_CAMPAIGNS.UPLOAD_PLAYERS.MODAL.DESCRIPTION.SOFT_RESET_PLAYER'),
};

const attributeLabels = {
  title: I18n.t('BONUS_CAMPAIGNS.UPLOAD_PLAYERS.MODAL.TITLE'),
  action: I18n.t('BONUS_CAMPAIGNS.UPLOAD_PLAYERS.MODAL.LABEL.ACTION'),
  uploadPlayers: I18n.t('BONUS_CAMPAIGNS.UPLOAD_PLAYERS.UPLOAD_PLAYERS'),
  status: I18n.t('BONUS_CAMPAIGNS.UPLOAD_PLAYERS.MODAL.LABEL.STATUS'),
};

export {
  attributeLabels,
  actions,
  actionsLabels,
  actionDescription,
};

export default attributeLabels;
