import I18n from 'i18n-js';

export enum actions {
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
}

export enum statuses {
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  INACTIVE = 'INACTIVE',
}

export enum departments {
  ADMINISTRATION = 'ADMINISTRATION',
  AFFILIATE = 'AFFILIATE',
  AFFILIATE_MANAGER = 'AFFILIATE_MANAGER',
  AFFILIATE_PARTNER = 'AFFILIATE_PARTNER',
  DIDLOGIC_OPERATOR = 'DIDLOGIC_OPERATOR',
  PLAYER = 'PLAYER',
  CS = 'CS',
  BI = 'BI',
  E2E = 'E2E',
  IGROMAT = 'IGROMAT',
  MARKETING = 'MARKETING',
  RETENTION = 'RETENTION',
  RFP = 'RFP',
  SALES = 'SALES',
  FINANCE = 'FINANCE',
  COMPLIANCE = 'COMPLIANCE',
  DEALING = 'DEALING',
  IB = 'IB',
  PAYMENT = 'PAYMENT',
  COMPLETE = 'COMPLETE',
}

export enum roles {
  EXECUTIVE = 'EXECUTIVE',
  TEAM_LEADER = 'TEAM_LEADER',
  MANAGER = 'MANAGER',
  HEAD_OF_DEPARTMENT = 'HEAD_OF_DEPARTMENT',
  MARKETING = 'MARKETING',
  COMPLIANCE = 'COMPLIANCE',
  COMPLIANCE_MANAGER = 'COMPLIANCE_MANAGER',
  E2E = 'E2E',
  BI = 'BI',
  AFFILIATE = 'AFFILIATE',
  PLAYER = 'PLAYER',
  AGENT = 'AGENT',
  SALES_LEAD_MANAGER = 'SALES_LEAD_MANAGER',
  SALES_MANAGER = 'SALES_MANAGER',
  SHIFT_RETENTION = 'SHIFT_RETENTION',
  SHIFT_SALES = 'SHIFT_SALES',
}

const closeReasons: Record<string, string> = {
  'OPERATOR_PROFILE.CLOSE_REASONS.PENDING_INVESTIGATION':
    'OPERATOR_PROFILE.CLOSE_REASONS.PENDING_INVESTIGATION',
  'OPERATOR_PROFILE.CLOSE_REASONS.TERMINATED':
    'OPERATOR_PROFILE.CLOSE_REASONS.TERMINATED',
};

const activeReasons: Record<string, string> = {
  'OPERATOR_PROFILE.ACTIVATE_REASONS.ACTIVATE':
    'OPERATOR_PROFILE.ACTIVATE_REASONS.ACTIVATE',
};

export type StatusAction = {
  action: actions,
  label: string,
  reasons: Record<string, string>,
};

type StatusActions = Record<string, Array<StatusAction>>;

export const statusActions: StatusActions = {
  [statuses.ACTIVE]: [
    {
      action: actions.CLOSED,
      label: 'Close',
      reasons: closeReasons,
    },
  ],
  [statuses.CLOSED]: [
    {
      action: actions.ACTIVE,
      label: 'Activate',
      reasons: activeReasons,
    },
  ],
};

export const statusesLabels: Record<statuses, string> = {
  [statuses.ACTIVE]: 'OPERATORS.STATUSES.ACTIVE',
  [statuses.CLOSED]: 'OPERATORS.STATUSES.CLOSED',
  [statuses.INACTIVE]: 'OPERATORS.STATUSES.INACTIVE',
};

export const departmentsLabels: Record<departments, string> = {
  [departments.ADMINISTRATION]: 'CONSTANTS.OPERATORS.DEPARTMENTS.ADMINISTRATION',
  [departments.AFFILIATE]: 'CONSTANTS.OPERATORS.DEPARTMENTS.AFFILIATE',
  [departments.AFFILIATE_MANAGER]: 'CONSTANTS.OPERATORS.DEPARTMENTS.AFFILIATE_MANAGER',
  [departments.AFFILIATE_PARTNER]: 'CONSTANTS.OPERATORS.DEPARTMENTS.AFFILIATE_PARTNER',
  [departments.DIDLOGIC_OPERATOR]: 'CONSTANTS.OPERATORS.DEPARTMENTS.DIDLOGIC_OPERATOR',
  [departments.PLAYER]: 'CONSTANTS.OPERATORS.DEPARTMENTS.PLAYER',
  [departments.CS]: 'CONSTANTS.OPERATORS.DEPARTMENTS.CS',
  [departments.BI]: 'CONSTANTS.OPERATORS.DEPARTMENTS.BI',
  [departments.E2E]: 'CONSTANTS.OPERATORS.DEPARTMENTS.E2E',
  [departments.IGROMAT]: 'CONSTANTS.OPERATORS.DEPARTMENTS.IGROMAT',
  [departments.MARKETING]: 'CONSTANTS.OPERATORS.DEPARTMENTS.MARKETING',
  [departments.RETENTION]: 'CONSTANTS.OPERATORS.DEPARTMENTS.RETENTION',
  [departments.RFP]: 'CONSTANTS.OPERATORS.DEPARTMENTS.RFP',
  [departments.SALES]: 'CONSTANTS.OPERATORS.DEPARTMENTS.SALES',
  [departments.FINANCE]: 'CONSTANTS.OPERATORS.DEPARTMENTS.FINANCE',
  [departments.COMPLIANCE]: 'CONSTANTS.OPERATORS.DEPARTMENTS.COMPLIANCE',
  [departments.DEALING]: 'CONSTANTS.OPERATORS.DEPARTMENTS.DEALING',
  [departments.IB]: 'CONSTANTS.OPERATORS.DEPARTMENTS.IB',
  [departments.PAYMENT]: 'CONSTANTS.OPERATORS.DEPARTMENTS.PAYMENT',
  [departments.COMPLETE]: 'CONSTANTS.OPERATORS.DEPARTMENTS.COMPLETE',
};

export const rolesLabels: Record<roles, string> = {
  [roles.EXECUTIVE]: 'CONSTANTS.OPERATORS.ROLES.EXECUTIVE',
  [roles.TEAM_LEADER]: 'CONSTANTS.OPERATORS.ROLES.TEAM_LEADER',
  [roles.MANAGER]: 'CONSTANTS.OPERATORS.ROLES.MANAGER',
  [roles.HEAD_OF_DEPARTMENT]: 'CONSTANTS.OPERATORS.ROLES.HEAD_OF_DEPARTMENT',
  [roles.MARKETING]: 'CONSTANTS.OPERATORS.ROLES.MARKETING',
  [roles.COMPLIANCE]: 'CONSTANTS.OPERATORS.ROLES.COMPLIANCE',
  [roles.COMPLIANCE_MANAGER]: 'CONSTANTS.OPERATORS.ROLES.COMPLIANCE_MANAGER',
  [roles.E2E]: 'CONSTANTS.OPERATORS.ROLES.E2E',
  [roles.BI]: 'CONSTANTS.OPERATORS.ROLES.BI',
  [roles.AFFILIATE]: 'CONSTANTS.OPERATORS.ROLES.AFFILIATE',
  [roles.PLAYER]: 'CONSTANTS.OPERATORS.ROLES.PLAYER',
  [roles.AGENT]: 'CONSTANTS.OPERATORS.ROLES.AGENT',
  [roles.SALES_LEAD_MANAGER]: 'CONSTANTS.OPERATORS.ROLES.SALES_LEAD_MANAGER',
  [roles.SALES_MANAGER]: 'CONSTANTS.OPERATORS.ROLES.SALES_MANAGER',
  [roles.SHIFT_RETENTION]: 'CONSTANTS.OPERATORS.ROLES.SHIFT_RETENTION',
  [roles.SHIFT_SALES]: 'CONSTANTS.OPERATORS.ROLES.SHIFT_SALES',
};

export const passwordPattern = /^(?!.*\s)(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{8,}$/;
export const passwordMaxSize = 16;
export const passwordCustomError = I18n.t('COMMON.OPERATOR_PASSWORD_INVALID');
