query LastNotificationsQuery {
  dashboard {
    lastNotification {
      uuid
      read
      priority
      createdAt
      type
      subtype
      details
      client {
        uuid
        fullName
        languageCode
      }
    }
  }
}
