export const genders = ['MALE', 'FEMALE'];

export const AGE_YEARS_CONSTRAINT = 18;

export const attributeLabels = {
  name: 'LEAD_PROFILE.PERSONAL.LABEL.FIRST_NAME',
  surname: 'LEAD_PROFILE.PERSONAL.LABEL.LAST_NAME',
  birthDate: 'LEAD_PROFILE.PERSONAL.LABEL.DATE_OF_BIRTH',
  gender: 'LEAD_PROFILE.PERSONAL.LABEL.GENDER',
  country: 'LEAD_PROFILE.PERSONAL.LABEL.COUNTRY',
  city: 'LEAD_PROFILE.PERSONAL.LABEL.CITY',
  phone: 'LEAD_PROFILE.PERSONAL.LABEL.PHONE',
  phoneCode: 'LEAD_PROFILE.PERSONAL.LABEL.PHONE_CODE',
  mobile: 'LEAD_PROFILE.PERSONAL.LABEL.MOBILE',
  mobileCode: 'LEAD_PROFILE.PERSONAL.LABEL.MOBILE_CODE',
  email: 'COMMON.EMAIL',
};
