import I18n from '../../../../../../../../utils/fake-i18n';

const attributeLabels = {
  lifeTime: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.LIFE_TIME'),
  providerId: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.PROVIDER'),
  gameId: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.GAMES'),
  name: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.NAME'),
  freeSpins: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.FREE_SPINS'),
  freeSpinReward: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.FREE_SPIN_REWARD'),
  betPerLine: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.BET_PER_LINE'),
  template: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.TEMPLATE'),
  prize: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.PRIZE'),
  wagering: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.WAGERING'),
  capping: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.CAPPING'),
  moneyPriority: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.MONEY_PRIORITY'),
  spinValue: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.SPIN_VALUE'),
  totalValue: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.TOTAL_VALUE'),
};

const attributePlaceholders = {
  days: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.PLACEHOLDERS.DAYS'),
  notSet: I18n.t('BONUS_CAMPAIGNS.REWARDS.FREE_SPIN.PLACEHOLDERS.NOT_SET'),
};

export {
  attributeLabels,
  attributePlaceholders,
};

