mutation RejectPaymentMutation(
  $typeAcc: String!
  $paymentId: String!
  $declineReason: String
) {
  payment {
    acceptPayment (
      typeAcc: $typeAcc
      paymentId: $paymentId
      declineReason: $declineReason
    )
  }
}
