import I18n from '../../../../../../../../../../utils/fake-i18n';

const attributeLabels = {
  bonusReward: I18n.t('CAMPAIGNS.SETTINGS.REWARDS.BONUS.LABEL.BONUS_REWARD'),
  grant: I18n.t('CAMPAIGNS.SETTINGS.REWARDS.BONUS.LABEL.GRANT'),
  capping: I18n.t('CAMPAIGNS.SETTINGS.REWARDS.BONUS.LABEL.CAPPING'),
  multiplier: I18n.t('CAMPAIGNS.SETTINGS.REWARDS.BONUS.LABEL.MULTIPLIER'),
  moneyPrior: I18n.t('CAMPAIGNS.SETTINGS.REWARDS.BONUS.LABEL.MONEY_TYPE_PRIOR'),
  maxBet: I18n.t('CAMPAIGNS.SETTINGS.REWARDS.BONUS.LABEL.MAX_BET'),
  lifeTime: I18n.t('CAMPAIGNS.SETTINGS.REWARDS.BONUS.LABEL.LIFE_TIME'),
};

const attributePlaceholders = {
  days: I18n.t('CAMPAIGNS.SETTINGS.REWARDS.BONUS.LABEL.PLACEHOLDERS.DAYS'),
  notSet: I18n.t('CAMPAIGNS.SETTINGS.REWARDS.BONUS.LABEL.PLACEHOLDERS.NOT_SET'),
};

export {
  attributeLabels,
  attributePlaceholders,
};
