export const attributeLabels = {
  currency: 'FEATURE_TOGGLES.MODALS.UPDATE_DEPOSIT_AMOUNT.CURRENCY',
  minDeposit: 'FEATURE_TOGGLES.MODALS.UPDATE_DEPOSIT_AMOUNT.MIN_DEPOSIT',
  maxDeposit: 'FEATURE_TOGGLES.MODALS.UPDATE_DEPOSIT_AMOUNT.MAX_DEPOSIT',
};
