export const validationErrors: Record<string, string> = {
  INVALID_PERCENTAGE: 'HIERARCHY.PROFILE_RULE_TAB.MODAL.PERCENTAGE_LIMIT_ERROR',
  REQUIRED: 'RULE_MODAL.SCHEDULE.ERRORS.OPERATOR_IS_REQUIRED',
};
