mutation ApprovePaymentMutation(
  $paymentId: String!
  $paymentMethod: String
  $typeAcc: String!
) {
  payment {
    acceptPayment (
      paymentId: $paymentId
      paymentMethod: $paymentMethod
      typeAcc: $typeAcc
    )
  }
}
