query AccountSymbolsQuery($accountUuid: String!) {
  tradingEngine {
    accountSymbols(accountUuid: $accountUuid) {
      name
      description
      digits
      symbolType
      securityName
      baseCurrency
      config(accountUuid: $accountUuid) {
        lotSize
        lotMin
        lotStep
        lotMax
        bidAdjustment
        askAdjustment
        percentage
      }
    }
  }
}
