import keyMirror from 'keymirror';

const kycStatuses = keyMirror({
  APPROVED: null,
  APPROVED_AWAITING_REVIEW: null,
  AWAITING_REVIEW: null,
  FAKE_DEPOSIT: null,
  FLAGGED_NON_COMPLIANT: null,
  NO_KYC: null,
  PARTIAL: null,
  PARTIAL_KYC_CAN_TRADE: null,
  PENDING: null,
  PRIOR_TO_REFUND: null,
  REFUND: null,
  REFUNDED_NON_COMPLIANT: null,
  REJECTED: null,
  RISK: null,
});

const kycStatusesLabels = {
  [kycStatuses.APPROVED]: 'KYC_REQUESTS.STATUS.APPROVED',
  [kycStatuses.APPROVED_AWAITING_REVIEW]: 'KYC_REQUESTS.STATUS.APPROVED_AWAITING_REVIEW',
  [kycStatuses.AWAITING_REVIEW]: 'KYC_REQUESTS.STATUS.AWAITING_REVIEW',
  [kycStatuses.FAKE_DEPOSIT]: 'KYC_REQUESTS.STATUS.FAKE_DEPOSIT',
  [kycStatuses.FLAGGED_NON_COMPLIANT]: 'KYC_REQUESTS.STATUS.FLAGGED_NON_COMPLIANT',
  [kycStatuses.NO_KYC]: 'KYC_REQUESTS.STATUS.NO_KYC',
  [kycStatuses.PARTIAL]: 'KYC_REQUESTS.STATUS.PARTIAL',
  [kycStatuses.PARTIAL_KYC_CAN_TRADE]: 'KYC_REQUESTS.STATUS.PARTIAL_KYC_CAN_TRADE',
  [kycStatuses.PENDING]: 'KYC_REQUESTS.STATUS.PENDING',
  [kycStatuses.PRIOR_TO_REFUND]: 'KYC_REQUESTS.STATUS.PRIOR_TO_REFUND',
  [kycStatuses.REFUND]: 'KYC_REQUESTS.STATUS.REFUND',
  [kycStatuses.REFUNDED_NON_COMPLIANT]: 'KYC_REQUESTS.STATUS.REFUNDED_NON_COMPLIANT',
  [kycStatuses.REJECTED]: 'KYC_REQUESTS.STATUS.REJECTED',
  [kycStatuses.RISK]: 'KYC_REQUESTS.STATUS.RISK',
};

export {
  kycStatuses,
  kycStatusesLabels,
};
