import keyMirror from 'keymirror';

export const notificationCenterTypes = keyMirror({
  WITHDRAWAL: null,
  DEPOSIT: null,
  ACCOUNT: null,
  KYC: null,
});

export const notificationCenterSubTypes = keyMirror({
  WITHDRAWAL_REQUEST_STATUS_FINANCE_TO_EXECUTE: null,
  WITHDRAWAL_REQUEST_STATUS_DEALING_REVIEW: null,
  WITHDRAWAL_REQUEST_STATUS_SALES_REVIEW: null,
  ACCOUNT_PASSWORD_RESET_REQUEST: null,
  WITHDRAWAL_REQUEST_CANCELLED: null,
  WITHDRAWAL_REQUEST_APPROVED: null,
  WITHDRAWAL_REQUEST_ATTEMPT: null,
  WITHDRAWAL_REQUEST_CREATED: null,
  KYC_DOCUMENT_UPLOADED: null,
  KYC_DOCUMENT_EXPIRED: null,
  ACCOUNT_MARGIN_CALL: null,
  ACCOUNT_PASSWORD_UPDATED: null,
  DEPOSIT_SUCCESSFUL: null,
  ACCOUNT_ARCHIVED: null,
  ACCOUNT_DISABLED: null,
  DEPOSIT_CREATED: null,
  ACCOUNT_CREATED: null,
  DEPOSIT_FAILED: null,
  KYC_APPROVED: null,
});

export const notificationCenterSubTypesLabels = {
  [notificationCenterSubTypes.WITHDRAWAL_REQUEST_STATUS_FINANCE_TO_EXECUTE]:
    'NOTIFICATION_CENTER.TYPES.WITHDRAWAL_REQUEST_STATUS_FINANCE_TO_EXECUTE',
  [notificationCenterSubTypes.WITHDRAWAL_REQUEST_STATUS_DEALING_REVIEW]:
    'NOTIFICATION_CENTER.TYPES.WITHDRAWAL_REQUEST_STATUS_DEALING_REVIEW',
  [notificationCenterSubTypes.WITHDRAWAL_REQUEST_STATUS_SALES_REVIEW]:
    'NOTIFICATION_CENTER.TYPES.WITHDRAWAL_REQUEST_STATUS_SALES_REVIEW',
  [notificationCenterSubTypes.ACCOUNT_PASSWORD_RESET_REQUEST]:
    'NOTIFICATION_CENTER.TYPES.ACCOUNT_PASSWORD_RESET_REQUEST',
  [notificationCenterSubTypes.ACCOUNT_PASSWORD_UPDATED]:
    'NOTIFICATION_CENTER.TYPES.ACCOUNT_PASSWORD_UPDATED',
  [notificationCenterSubTypes.WITHDRAWAL_REQUEST_CANCELLED]: 'NOTIFICATION_CENTER.TYPES.WITHDRAWAL_REQUEST_CANCELLED',
  [notificationCenterSubTypes.WITHDRAWAL_REQUEST_APPROVED]: 'NOTIFICATION_CENTER.TYPES.WITHDRAWAL_REQUEST_APPROVED',
  [notificationCenterSubTypes.WITHDRAWAL_REQUEST_ATTEMPT]: 'NOTIFICATION_CENTER.TYPES.WITHDRAWAL_REQUEST_ATTEMPT',
  [notificationCenterSubTypes.WITHDRAWAL_REQUEST_CREATED]: 'NOTIFICATION_CENTER.TYPES.WITHDRAWAL_REQUEST_CREATED',
  [notificationCenterSubTypes.KYC_DOCUMENT_UPLOADED]: 'NOTIFICATION_CENTER.TYPES.KYC_DOCUMENT_UPLOADED',
  [notificationCenterSubTypes.KYC_DOCUMENT_EXPIRED]: 'NOTIFICATION_CENTER.TYPES.KYC_DOCUMENT_EXPIRED',
  [notificationCenterSubTypes.ACCOUNT_MARGIN_CALL]: 'NOTIFICATION_CENTER.TYPES.ACCOUNT_MARGIN_CALL',
  [notificationCenterSubTypes.DEPOSIT_SUCCESSFUL]: 'NOTIFICATION_CENTER.TYPES.DEPOSIT_SUCCESSFUL',
  [notificationCenterSubTypes.ACCOUNT_ARCHIVED]: 'NOTIFICATION_CENTER.TYPES.ACCOUNT_ARCHIVED',
  [notificationCenterSubTypes.ACCOUNT_DISABLED]: 'NOTIFICATION_CENTER.TYPES.ACCOUNT_DISABLED',
  [notificationCenterSubTypes.DEPOSIT_CREATED]: 'NOTIFICATION_CENTER.TYPES.DEPOSIT_CREATED',
  [notificationCenterSubTypes.ACCOUNT_CREATED]: 'NOTIFICATION_CENTER.TYPES.ACCOUNT_CREATED',
  [notificationCenterSubTypes.DEPOSIT_FAILED]: 'NOTIFICATION_CENTER.TYPES.DEPOSIT_FAILED',
  [notificationCenterSubTypes.KYC_APPROVED]: 'NOTIFICATION_CENTER.TYPES.KYC_APPROVED',
};
