import keyMirror from 'keymirror';

const statuses = keyMirror({
  APPROVED: null,
  CANCELED: null,
  COMPLETED: null,
  FAILED: null,
  PENDING: null,
  REJECTED: null,
});

const tradingStatuses = keyMirror({
  PAYMENT_PENDING: null,
  PAYMENT_FAILED: null,
  PAYMENT_REFUSED: null,
  PAYMENT_CHARGEBACK: null,
  PAYMENT_COMPLETED: null,
  TRANSACTION_FAILED: null,
  TRANSACTION_COMPLETED: null,
  PAYMENT_CANCELED: null,
  PAYMENT_APPROVED: null,
});

const statusMapper = {
  [statuses.COMPLETED]: [
    tradingStatuses.PAYMENT_COMPLETED,
  ],
  [statuses.APPROVED]: [
    tradingStatuses.PAYMENT_APPROVED,
  ],
  [statuses.FAILED]: [
    tradingStatuses.PAYMENT_FAILED,
    tradingStatuses.TRANSACTION_FAILED,
  ],
  [statuses.PENDING]: [
    tradingStatuses.PAYMENT_PENDING,
  ],
  [statuses.REJECTED]: [tradingStatuses.PAYMENT_REFUSED],
  [statuses.CANCELED]: [tradingStatuses.PAYMENT_CANCELED],
};

const methods = keyMirror({
  CREDIT_CARD: null,
  PAYPAL: null,
  PAYTRIO: null,
  SKRILL: null,
  ENFINS: null,
  CASHIER: null,
  VOGUEPAY: null,
  CHARGEBACK: null,
  CRYPTOCURRENCY_EXTERNAL: null,
});

const aggregators = keyMirror({
  MANUAL: null,
  CASHIER: null,
  INTERNAL: null,
});

const manualPaymentMethods = keyMirror({
  BONUS: null,
  CHARGEBACK: null,
  CREDIT_CARD: null,
  ELECTRONIC: null,
  EXTERNAL: null,
  INTERNAL_TRANSFER: null,
  MIGRATION: null,
  PAYRETAILERS: null,
  RECALL: null,
  SYSTEM: null,
  WIRE: null,
  REFERRAL_BONUS: null,
});

const tradingTypes = keyMirror({
  CREDIT_IN: null,
  CREDIT_OUT: null,
  DEPOSIT: null,
  INACTIVITY_FEE: null,
  INTEREST_RATE: null,
  TRANSFER_IN: null,
  TRANSFER_OUT: null,
  WITHDRAW: null,
});

const tradingTypesLabels = {
  [tradingTypes.DEPOSIT]: 'COMMON.PAYMENT_TYPE.DEPOSIT',
  [tradingTypes.WITHDRAW]: 'COMMON.PAYMENT_TYPE.WITHDRAW',
  [tradingTypes.INTEREST_RATE]: 'COMMON.PAYMENT_TYPE.INTEREST_RATE',
  DEMO_DEPOSIT: 'COMMON.PAYMENT_TYPE.DEPOSIT',
  // Special type for transaction with type FEE
  FEE: 'COMMON.PAYMENT_TYPE.FEE',
  [tradingTypes.INACTIVITY_FEE]: 'COMMON.PAYMENT_TYPE.INACTIVITY_FEE',
  [tradingTypes.TRANSFER_IN]: 'COMMON.PAYMENT_TYPE.TRANSFER_IN',
  [tradingTypes.TRANSFER_OUT]: 'COMMON.PAYMENT_TYPE.TRANSFER_OUT',
  [tradingTypes.CREDIT_IN]: 'COMMON.PAYMENT_TYPE.CREDIT_IN',
  [tradingTypes.CREDIT_OUT]: 'COMMON.PAYMENT_TYPE.CREDIT_OUT',
};

const statusesLabels = {
  [statuses.PENDING]: 'COMMON.PAYMENT_STATUS.PENDING',
  [statuses.APPROVED]: 'COMMON.PAYMENT_STATUS.APPROVED',
  [statuses.REJECTED]: 'COMMON.PAYMENT_STATUS.REJECTED',
  [statuses.CANCELED]: 'COMMON.PAYMENT_STATUS.CANCELED',
  [statuses.FAILED]: 'COMMON.PAYMENT_STATUS.FAILED',
  [statuses.COMPLETED]: 'COMMON.PAYMENT_STATUS.COMPLETED',
};

const methodsLabels = {
  [methods.SKRILL]: 'CONSTANTS.PAYMENT.PAYMENT_METHODS.SKRILL',
  [methods.PAYPAL]: 'CONSTANTS.PAYMENT.PAYMENT_METHODS.PAYPAL',
  [methods.CREDIT_CARD]: 'CONSTANTS.PAYMENT.PAYMENT_METHODS.CREDIT_CARD',
  [methods.PAYTRIO]: 'CONSTANTS.PAYMENT.PAYMENT_METHODS.PAYTRIO',
  [methods.CASHIER]: 'CONSTANTS.PAYMENT.PAYMENT_METHODS.CASHIER',
  [methods.CRYPTOCURRENCY_EXTERNAL]: 'CONSTANTS.PAYMENT.PAYMENT_METHODS.CRYPTOCURRENCY_EXTERNAL',
  [methods.ENFINS]: 'CONSTANTS.PAYMENT.PAYMENT_METHODS.ENFINS',
  [methods.VOGUEPAY]: 'CONSTANTS.PAYMENT.PAYMENT_METHODS.VOGUEPAY',
  [methods.B2CRYPTO]: 'CONSTANTS.PAYMENT.PAYMENT_METHODS.B2CRYPTO',
  [methods.PAYRETAILERS]: 'CONSTANTS.PAYMENT.PAYMENT_METHODS.PAYRETAILERS',
  [methods.WIRECAPITAL]: 'CONSTANTS.PAYMENT.PAYMENT_METHODS.WIRECAPITAL',
  [methods.EFTPAY]: 'CONSTANTS.PAYMENT.PAYMENT_METHODS.EFTPAY',
};

const aggregatorsLabels = {
  [aggregators.MANUAL]: 'CONSTANTS.PAYMENT.PAYMENT_AGGREGATORS.MANUAL',
  [aggregators.CASHIER]: 'CONSTANTS.PAYMENT.PAYMENT_AGGREGATORS.CASHIER',
  [aggregators.INTERNAL]: 'CONSTANTS.PAYMENT.PAYMENT_AGGREGATORS.INTERNAL',
};

const manualPaymentMethodsLabels = {
  [manualPaymentMethods.SYSTEM]: 'CONSTANTS.TRANSACTIONS.FILTER_FORM.PAYMENT_ACCOUNTS.SYSTEM',
  [manualPaymentMethods.CREDIT_CARD]: 'CONSTANTS.TRANSACTIONS.FILTER_FORM.PAYMENT_ACCOUNTS.CREDIT_CARD',
  [manualPaymentMethods.WIRE]: 'CONSTANTS.TRANSACTIONS.FILTER_FORM.PAYMENT_ACCOUNTS.WIRE',
  [manualPaymentMethods.EXTERNAL]: 'CONSTANTS.TRANSACTIONS.FILTER_FORM.PAYMENT_ACCOUNTS.EXTERNAL',
  [manualPaymentMethods.MIGRATION]: 'CONSTANTS.TRANSACTIONS.FILTER_FORM.PAYMENT_ACCOUNTS.MIGRATION',
  [manualPaymentMethods.INTERNAL_TRANSFER]: 'CONSTANTS.TRANSACTIONS.FILTER_FORM.PAYMENT_ACCOUNTS.INTERNAL_TRANSFER',
  [manualPaymentMethods.ELECTRONIC]: 'CONSTANTS.TRANSACTIONS.FILTER_FORM.PAYMENT_ACCOUNTS.ELECTRONIC',
  [manualPaymentMethods.BONUS]: 'CONSTANTS.TRANSACTIONS.FILTER_FORM.PAYMENT_ACCOUNTS.BONUS',
  [manualPaymentMethods.PAYRETAILERS]: 'CONSTANTS.TRANSACTIONS.FILTER_FORM.PAYMENT_ACCOUNTS.PAYRETAILERS',
  [manualPaymentMethods.RECALL]: 'CONSTANTS.TRANSACTIONS.FILTER_FORM.PAYMENT_ACCOUNTS.RECALL',
  [manualPaymentMethods.CHARGEBACK]: 'CONSTANTS.TRANSACTIONS.FILTER_FORM.PAYMENT_ACCOUNTS.CHARGEBACK',
  [manualPaymentMethods.REFERRAL_BONUS]: 'CONSTANTS.TRANSACTIONS.FILTER_FORM.PAYMENT_ACCOUNTS.REFERRAL_BONUS',
};

export {
  statuses,
  tradingStatuses,
  statusesLabels,
  statusMapper,
  methods,
  aggregators,
  manualPaymentMethods,
  methodsLabels,
  aggregatorsLabels,
  manualPaymentMethodsLabels,
  tradingTypes,
  tradingTypesLabels,
};
