import keyMirror from 'keymirror';
import { I18n } from 'react-redux-i18n';

const actions = keyMirror({
  LOCK: null,
  UNLOCK: null,
});
const authors = {
  OPERATOR: 'operator',
  PROFILE: 'profile',
  BONUS: 'bonus',
};
const types = {
  DEPOSIT: 'deposit',
  WITHDRAW: 'withdraw',
};
const reasons = {
  [actions.LOCK]: {
    'PLAYER_PROFILE.WALLET.LOCK.REASONS.SUSPECTED_FRAUD':
      I18n.t('PLAYER_PROFILE.WALLET.LOCK.REASONS.SUSPECTED_FRAUD'),
    'PLAYER_PROFILE.WALLET.LOCK.REASONS.SUSPECTED_ML':
      I18n.t('PLAYER_PROFILE.WALLET.LOCK.REASONS.SUSPECTED_ML'),
    'PLAYER_PROFILE.WALLET.LOCK.REASONS.SUSPECTED_IDENTITY_THEFT':
      I18n.t('PLAYER_PROFILE.WALLET.LOCK.REASONS.SUSPECTED_IDENTITY_THEFT'),
  },
  [actions.UNLOCK]: {
    'PLAYER_PROFILE.WALLET.UNLOCK.REASONS.KYC_PROVIDED':
      I18n.t('PLAYER_PROFILE.WALLET.UNLOCK.REASONS.KYC_PROVIDED'),
    'PLAYER_PROFILE.WALLET.UNLOCK.REASONS.DECLARATION_PROVIDED':
      I18n.t('PLAYER_PROFILE.WALLET.UNLOCK.REASONS.DECLARATION_PROVIDED'),
    'PLAYER_PROFILE.WALLET.UNLOCK.REASONS.ID_PROVIDED':
      I18n.t('PLAYER_PROFILE.WALLET.UNLOCK.REASONS.ID_PROVIDED'),
  },
};

export {
  actions,
  authors,
  types,
  reasons,
};
