mutation UploadLeadsMutation(
  $file: Upload!
) {
  leads {
    uploadLeads (
      file: $file
    ) {
      failedLeads {
        name
        surname
        phone
        email
        mobile
        country
        source
        salesAgent
        birthDate
        affiliate
        gender
        city
        language
        failureReason
      }
      failedLeadsCount
      createdLeadsCount
    }
  }
}
