mutation CreateScheduleMutation(
  $affiliateUuid: String!,
  $activated: Boolean,
  $totalLimit: Int,
  $day: String,
  $workingHoursFrom: String,
  $workingHoursTo: String,
  $countrySpreads: [PartnerSchedule__Input],
) {
  partner {
    createSchedule (
      affiliateUuid: $affiliateUuid,
      activated: $activated,
      totalLimit: $totalLimit,
      day: $day,
      workingHoursFrom: $workingHoursFrom,
      workingHoursTo: $workingHoursTo,
      countrySpreads: $countrySpreads,
    )
  }
}
