import I18n from '../../../../../../../../utils/fake-i18n';

const attributeLabels = {
  name: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.NAME'),
  startDate: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.START_DATE'),
  endDate: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.END_DATE'),
  availabilityDateRange: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.AVAILABILITY_DATE_RANGE'),
  providerId: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.PROVIDER'),
  gameId: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.GAME'),
  freeSpinsAmount: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.FREE_SPINS_AMOUNT'),
  prize: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.PRIZE'),
  capping: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.CAPPING'),
  multiplier: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.MULTIPLIER'),
  bonusLifeTime: I18n.t('PLAYER_PROFILE.FREE_SPIN.MODAL_CREATE.ATTRIBUTES_LABELS.BONUS_LIFE_TIME'),
};

export {
  attributeLabels,
};
