export const attributeLabels = {
  searchBy: 'TRADING_ENGINE.ACCOUNT_PROFILE.FEED.FILTER_FORM.LABELS.SEARCH_BY',
  actionType: 'TRADING_ENGINE.ACCOUNT_PROFILE.FEED.FILTER_FORM.LABELS.ACTION_TYPES',
  creationDateFrom: 'TRADING_ENGINE.ACCOUNT_PROFILE.FEED.FILTER_FORM.LABELS.CREATION_DATE_FROM',
  creationDateTo: 'TRADING_ENGINE.ACCOUNT_PROFILE.FEED.FILTER_FORM.LABELS.CREATION_DATE_TO',
  orderId: 'TRADING_ENGINE.ACCOUNT_PROFILE.FEED.FILTER_FORM.LABELS.ORDER_ID',
};
