query SymbolQuery($symbolName: String!) {
  tradingEngine {
    symbol(symbolName: $symbolName) {
      symbol
      source
      digits
      description
      securityName
      bidSpread
      askSpread
      stopsLevel
      lotSize
      percentage
      baseCurrency
      quoteCurrency
      lotMin
      lotMax
      lotStep
      symbolType
      sourceSymbol {
        filtration {
          filterSmoothing
          discardFiltrationLevel
          softFilter
          softFiltrationLevel
          hardFilter
          hardFiltrationLevel
        }
      }
      defaultFiltration
      filtration {
        filterSmoothing
        discardFiltrationLevel
        softFilter
        softFiltrationLevel
        hardFilter
        hardFiltrationLevel
      }
      swapConfigs {
        enable
        type
        long
        short
        rollover
      }
      backgroundColor
      symbolSessions {
        dayOfWeek
        quote {
          openTime
          closeTime
        }
        trade {
          openTime
          closeTime
        }
      }
    }
  }
}
