export const types = [{
  value: 'BUY',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.BUY',
}, {
  value: 'BUY_LIMIT',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.BUY_LIMIT',
}, {
  value: 'BUY_STOP_LIMIT',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.BUY_STOP_LIMIT',
}, {
  value: 'BUY_MARKET',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.BUY_MARKET',
}, {
  value: 'BUY_STOP',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.BUY_STOP',
}, {
  value: 'CREDIT',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.CREDIT',
}, {
  value: 'SELL',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.SELL',
}, {
  value: 'SELL_LIMIT',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.SELL_LIMIT',
}, {
  value: 'SELL_STOP_LIMIT',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.SELL_STOP_LIMIT',
}, {
  value: 'SELL_MARKET',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.SELL_MARKET',
}, {
  value: 'SELL_STOP',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.SELL_STOP',
}];

export const statuses = [{
  value: 'CLOSED',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.STATUSES.CLOSED',
}, {
  value: 'OPEN',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.STATUSES.OPEN',
}, {
  value: 'PENDING',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.STATUSES.PENDING',
}, {
  value: 'CANCELED',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.STATUSES.CANCELED',
}];

export const tradeStatusesColor = {
  PENDING: 'color-info',
  CLOSED: 'color-danger',
  OPEN: 'color-success',
};
