import I18n from '../../../../../../../utils/fake-i18n';

const attributeLabels = {
  name: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.NAME'),
  bonusReward: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.BONUS_REWARD'),
  grant: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.GRANT'),
  limits: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.LIMITS'),
  multiplier: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.MULTIPLIER'),
  multipliersType: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.MULTIPLIERS_TYPE'),
  moneyPrior: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.MONEY_TYPE_PRIOR'),
  lifeTime: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.LIFE_TIME'),
  maxBet: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.MAX_BET'),
  maxGrantedAmount: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.MAX_GRANTED_AMOUNT'),
  maxGrantAmount: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.MAX_GRANTED_AMOUNT'),
  template: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.TEMPLATE'),
  wageringRequirement: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.WAGERING_REQUIREMENT'),
  lockAmountStrategy: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.LOCK_AMOUNT_STRATEGY'),
  capping: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.CAPPING'),
};

const attributePlaceholders = {
  days: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.PLACEHOLDERS.DAYS'),
  notSet: I18n.t('BONUS_CAMPAIGNS.REWARDS.BONUS.PLACEHOLDERS.NOT_SET'),
};

export {
  attributeLabels,
  attributePlaceholders,
};
