query TransactionsQuery(
  $args: TradingEngineTransactionSearch__Input
) {
  tradingEngine {
    transactions(args: $args) {
      content {
        id
        accountLogin
        type
        amount
        createdAt
        comment
      }
      page
      number
      totalElements
      size
      last
    }
  }
}
