query CallHistoryQuery($uuid: String!, $args: CallHistorySearch__Input!) {
  callHistory(uuid: $uuid, args: $args) {
    page
    last
    content {
      uuid
      operatorUuid
      callSystem
      createdAt
      operator {
        uuid
        fullName
      }
    }
  }
}
