query AccountsQuery($args: TradingEngineAccountSearch__Input) {
  tradingEngine {
    accounts (args: $args) {
      content {
        uuid
        name
        login
        group
        credit
        profileUuid
        registrationDate
        leverage
        balance
        accountType
      }
      page
      number
      totalElements
      size
      last
    }
  }
}
