import I18n from '../../../../../../../../utils/fake-i18n';

const attributeLabels = {
  searchBy: I18n.t('CONSTANTS.FREE_SPINS.FILTER_FORM.ATTRIBUTES_LABELS.SEARCH_BY'),
  assigned: I18n.t('CONSTANTS.FREE_SPINS.FILTER_FORM.ATTRIBUTES_LABELS.ASSIGNED'),
  provider: I18n.t('CONSTANTS.FREE_SPINS.FILTER_FORM.ATTRIBUTES_LABELS.PROVIDER'),
  game: I18n.t('CONSTANTS.FREE_SPINS.FILTER_FORM.ATTRIBUTES_LABELS.GAME'),
  startDate: I18n.t('CONSTANTS.FREE_SPINS.FILTER_FORM.ATTRIBUTES_LABELS.START_DATE'),
  endDate: I18n.t('CONSTANTS.FREE_SPINS.FILTER_FORM.ATTRIBUTES_LABELS.END_DATE'),
};

export default {
  attributeLabels,
};
