query WithdrawalAmountQuery(
  $dateFrom: String
  $dateTo: String
  $zoneId: String
  $summary: [ChartDataSummary__Input]
) {
  dashboard {
    withdrawalAmountStatistic(
      dateFrom: $dateFrom
      dateTo: $dateTo
      zoneId: $zoneId
      summary: $summary
    ) {
      items {
        entryValue
        entryDate
      }
      summary {
        value
        type
      }
    }
  }
}
