import I18n from '../../../../utils/fake-i18n';

const attributeLabels = {
  header: I18n.t('BONUS_CAMPAIGNS.CURRENCY_CALC_MODAL.HEADER'),
  minDeposit: I18n.t('BONUS_CAMPAIGNS.CURRENCY_CALC_MODAL.BODY.MIN_DEPOSIT'),
  recalc: I18n.t('BONUS_CAMPAIGNS.CURRENCY_CALC_MODAL.BODY.RECALC'),
  recalcWarning: I18n.t('BONUS_CAMPAIGNS.CURRENCY_CALC_MODAL.BODY.RECALC_WARNING'),
  currency: I18n.t('BONUS_CAMPAIGNS.CURRENCY_CALC_MODAL.BODY.CURRENCY'),
  rate: I18n.t('BONUS_CAMPAIGNS.CURRENCY_CALC_MODAL.BODY.RATE'),
  calculated: I18n.t('BONUS_CAMPAIGNS.CURRENCY_CALC_MODAL.BODY.CALCULATED'),
  customized: I18n.t('BONUS_CAMPAIGNS.CURRENCY_CALC_MODAL.BODY.CUSTOMIZED'),
};

export default attributeLabels;
