query SymbolQuery($symbol: String!, $accountUuid: String!, $pricesSize: Int!) {
  tradingEngine {
    symbol(symbolName: $symbol) {
      digits
      config(accountUuid: $accountUuid) {
        bidAdjustment
        askAdjustment
      }
      prices(size: $pricesSize) {
        name
        ask
        bid
        time
      }
      currentHolidays {
        id
        description
        date
        timeRange {
          from
          to
        }
      }
    }
  }
}
