mutation ChangeOriginalAgentTradingActivityMutation(
  $tradeId: Int!
  $agentId: String!
  $platformType: String
) {
  tradingActivity {
    changeOriginalAgent(
      tradeId: $tradeId
      agentId: $agentId
      platformType: $platformType
    )
  }
}
