query GetClientCallbackQuery(
  $id: String!,
) {
  clientCallback(
    id: $id,
  ) {
    _id
    operatorId
    userId
    callbackId
    callbackTime
    status
    creationTime
    updateTime
    reminder
    operator {
      fullName
    }
    client {
      fullName
    }
    note {
      _id
      noteId
      content
      pinned
    }
  }
}
