export default {
  REPORTS: {
    PLAYER_LIABILITY_VIEW: 'mga_report;GET;/reports/player-liability',
    PLAYER_LIABILITY_FILES_VIEW: 'mga_report;GET;/reports/player-liability/files',
    PLAYER_LIABILITY_FILE_VIEW: 'mga_report;GET;/reports/player-liability/files/{file}',
    VAT_VIEW: 'mga_report;GET;/reports/vat',
  },
  OPERATORS: {
    OPERATORS_LIST_VIEW: 'operator;GET;/operators',
    PROFILE_VIEW: 'operator;GET;/operators/{uuid}',
    CREATE: 'operator;POST;/operators',
    OPERATOR_SEND_INVITATION: 'operator;PUT;/operators/{uuid}/send/invitation',
    ADD_AUTHORITY: 'auth;POST;/credentials/{uuid}/authorities',
    DELETE_AUTHORITY: 'auth;DELETE;/credentials/{uuid}/authorities',
  },
  USER_PROFILE: {
    SEND_ACTIVATION_LINK: 'profile;POST;/profiles/{playerUUID}/send-activation-link',
    GET_RESET_PASSWORD_TOKEN: 'auth;GET;/password/reset-token?playerUUID={playerUUID}',
    SUSPEND: 'profile;PUT;/profiles/{playerUUID}/suspend',
    BLOCK: 'profile;PUT;/profiles/{playerUUID}/block',
    UNBLOCK: 'profile;PUT;/profiles/{playerUUID}/unblock',
    PROLONG: 'profile;PUT;/profiles/{playerUUID}/suspend/prolong',
    REMOVE: 'profile;PUT;/profiles/{playerUUID}/resume',
    PROFILE_VIEW: 'profile;GET;/profiles/{playerUUID}',
    ADD_TO_CAMPAIGN: 'promotion;PUT;/campaigns/{id}/players-list/{playerUUID}',
    ADD_TAG: 'profile;POST;/profiles/{playerUUID}/tags',
    DELETE_TAG: 'profile;DELETE;/profiles/{playerUUID}/tags/{tagId}',
    LOCK_DEPOSIT: 'payment;POST;/lock/deposit',
    LOCK_WITHDRAW: 'payment;POST;/lock/withdraw',
    UNLOCK_DEPOSIT: 'payment;POST;/lock/{playerUUID}/deposit',
    UNLOCK_WITHDRAW: 'payment;POST;/lock/{playerUUID}/withdraw',
    UNLOCK_LOGIN: 'auth;DELETE;/credentials/{playerUUID}/lock',
    GET_LOGIN_LOCK: 'auth;GET;/credentials/{uuid}/lock',
    GET_PAYMENT_LOCKS: 'payment;GET;/lock/{uuid}',
    UPDATE_MARKETING_SETTINGS: 'profile;PUT;/profiles/{playerUUID}/subscription',
    REQUEST_KYC: 'profile;POST;/kyc/{playerUUID}/request',
    KYC_VERIFY_ALL: 'profile;POST;/kyc/{playerUUID}/verify',
    KYC_VERIFY: 'profile;POST;/kyc/{playerUUID}/{type}/verify',
    KYC_REJECT: 'profile;DELETE;/kyc/{playerUUID}/{type}',
    UPDATE_PROFILE: 'profile;PUT;/profiles/{playerUUID}',
    VIEW_FILES: 'profile;GET;/files/{playerUUID}',
    VIEW_FILE: 'profile;GET;/kyc/download/{fileId}',
    UPLOAD_FILE: 'profile;POST;/files',
    VERIFY_FILE: 'profile;PUT;files/{uuid}/status/verify',
    REFUSE_FILE: 'profile;DELETE;files/{uuid}/status/refuse',
    DELETE_FILE: 'profile;DELETE;files/{playerUUID}/{fileUUID}',
    VERIFY_PHONE: 'profile;POST;/verification/{playerUUID}/phone',
    VERIFY_EMAIL: 'profile;POST;/verification/{playerUUID}',
  },
  PAYMENTS: {
    APPROVE_WITHDRAW: 'payment;POST;/payments/{playerUUID}/{paymentId}/approve',
    REFUSE_WITHDRAW: 'payment;POST;/payments/{playerUUID}/{paymentId}/refuse',
    CHARGEBACK_DEPOSIT: 'payment;POST;/payments/{playerUUID}/{paymentId}/chargeback',
  },
  NOTES: {
    ADD_NOTE: 'note;POST;/notes',
    UPDATE_NOTE: 'note;PUT;/notes/{noteId}',
    DELETE_NOTE: 'note;DELETE;/notes/{noteId}',
    VIEW_NOTES: 'note;GET;/notes',
  },
};
