query ReferralsQuery($uuid: String!) {
  referrals(uuid: $uuid) {
    referralInfo {
      name
      profileUuid
      languageCode
      countryCode
      registrationDate
    }
    bonusType
    ftdInfo {
      date
      amount
      currency
      normalizedAmount
    }
    remuneration {
      date
      amount
      currency
      normalizedAmount
    }
    acquisition {
      acquisitionStatus
      retentionOperator {
        fullName
        hierarchy {
          parentBranches {
            name
            branchType
            parentBranch {
              name
              branchType
            }
          }
        }
      }
      retentionStatus
      salesOperator {
        fullName
        hierarchy {
          parentBranches {
            name
            branchType
            parentBranch {
              name
              branchType
            }
          }
        }
      }
      salesStatus
    }
  }
}
