query LeadCallbacksQuery(
  $callbackTimeFrom: String
  $callbackTimeTo: String
  $limit: Int
) {
  leadCallbacks(
    callbackTimeFrom: $callbackTimeFrom
    callbackTimeTo: $callbackTimeTo
    limit: $limit
    ) @connection(key: "LEAD_CALLBACKS_HEADER_CALENDAR") {
    content {
      _id
      callbackId
      callbackTime
      lead {
        fullName
      }
    }
  }
}
