query LeadCallbacksQuery(
  $callbackTimeFrom: String
  $callbackTimeTo: String
  $page: Page__Input
) {
  leadCallbacks(
    callbackTimeFrom: $callbackTimeFrom
    callbackTimeTo: $callbackTimeTo
    page: $page
    ) @connection(key: "LEAD_CALLBACKS_HEADER_CALENDAR") {
    content {
      _id
      callbackId
      callbackTime
      lead {
        fullName
      }
    }
  }
}
