mutation ChangeScheduleStatusMutation(
  $affiliateUuid: String!
  $data: [PartnerScheduleStatus__Input]
) {
  partner {
    changeScheduleStatus (
      affiliateUuid: $affiliateUuid
      data: $data
    )
  }
}
