
export const orderTypes = {
  BUY: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.BUY',
  BUY_LIMIT: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.BUY_LIMIT',
  BUY_STOP_LIMIT: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.BUY_STOP_LIMIT',
  BUY_MARKET: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.BUY_MARKET',
  BUY_STOP: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.BUY_STOP',
  CREDIT: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.CREDIT',
  SELL: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.SELL',
  SELL_LIMIT: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.SELL_LIMIT',
  SELL_STOP_LIMIT: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.SELL_STOP_LIMIT',
  SELL_MARKET: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.SELL_MARKET',
  SELL_STOP: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.SELL_STOP',
};

export const orderStatuses = {
  OPEN: 'CLIENT_PROFILE.TRADING_ACTIVITY.FILTER_FORM.STATUSES.OPEN',
  CLOSED: 'CLIENT_PROFILE.TRADING_ACTIVITY.FILTER_FORM.STATUSES.CLOSED',
  PENDING: 'CLIENT_PROFILE.TRADING_ACTIVITY.FILTER_FORM.STATUSES.PENDING',
  CANCELED: 'CLIENT_PROFILE.TRADING_ACTIVITY.FILTER_FORM.STATUSES.CANCELED',
};
