query TradingAccountsQuery(
  $searchKeyword: String
  $accountType: String
  $platformType: String
  $archived: Boolean
  $page: Page__Input
) {
  tradingAccounts (
    searchKeyword: $searchKeyword
    platformType: $platformType
    accountType: $accountType
    archived: $archived
    page: $page
  ) {
    content {
      uuid
      name
      login
      group
      accountUUID
      platformType
      credit
      profile {
        uuid
        fullName
      }
      affiliate {
        source
      }
      createdAt
      leverage
      balance
      archived
      accountType
      currency
    }
    totalElements
    size
    last
    number
  }
}
