query OrdersQuery($args: TradingEngineOrdersSearch__Input) {
  tradingEngine {
    orders(args: $args) {
      content {
        id
        accountLogin
        tradeType
        symbol
        symbolAlias
        direction
        digits
        takeProfit
        stopLoss
        openPrice
        closePrice
        marginRate
        volumeUnits
        volumeLots
        commission
        swaps
        status
        group
        margin
        pnl {
          gross
          net
        }
        time {
          creation
          modification
          expiration
          closing
        }
        comment
        type
        account {
          currency
        }
        symbolConfig {
          lotSize
          bidAdjustment
          askAdjustment
        }
      }
      page
      number
      totalElements
      size
      last
    }
  }
}
