import keyMirror from 'keymirror';
import I18n from '../../../../../../../../utils/fake-i18n';

const filterFormAttributeLabels = {
  keyword: I18n.t('PLAYER_PROFILE.GAME_ACTIVITY.FILTER_FORM.KEYWORD_LABEL'),
  aggregators: I18n.t('PLAYER_PROFILE.GAME_ACTIVITY.FILTER_FORM.AGGREGATORS_LABEL'),
  providers: I18n.t('PLAYER_PROFILE.GAME_ACTIVITY.FILTER_FORM.PROVIDERS_LABEL'),
  games: I18n.t('PLAYER_PROFILE.GAME_ACTIVITY.FILTER_FORM.GAMES_LABEL'),
  gameTypes: I18n.t('PLAYER_PROFILE.GAME_ACTIVITY.FILTER_FORM.GAME_TYPES_LABEL'),
  betTypes: I18n.t('PLAYER_PROFILE.GAME_ACTIVITY.FILTER_FORM.BET_TYPES_LABEL'),
  winTypes: I18n.t('PLAYER_PROFILE.GAME_ACTIVITY.FILTER_FORM.WIN_TYPES_LABEL'),
  startDate: I18n.t('PLAYER_PROFILE.GAME_ACTIVITY.FILTER_FORM.START_DATE_LABEL'),
  endDate: I18n.t('PLAYER_PROFILE.GAME_ACTIVITY.FILTER_FORM.END_DATE_LABEL'),
  dateRange: I18n.t('PLAYER_PROFILE.GAME_ACTIVITY.FILTER_FORM.ACTIVITY_DATE_RANGE'),
};

export const gameRoundTypes = keyMirror({
  ADJUSTMENT: null,
  FREE_SPIN: null,
  SPORTBET: null,
  OTHER: null,
  SPIN: null,
  BONUS_ROUND_FREESPIN: null,
  BONUS_ROUND_BONUS: null,
  BONUS_ROUND_CHANCE: null,
  BONUS_ROUND_CARD: null,
});

export default filterFormAttributeLabels;
