export enum actions {
  VERIFY = 'VERIFY',
  REFUSE = 'REFUSE',
}

export enum documentsCategories {
  DOCUMENT_VERIFICATION = 'DOCUMENT_VERIFICATION',
  ADDRESS_VERIFICATION = 'ADDRESS_VERIFICATION',
  OTHER = 'OTHER',
}

export enum documentsType {
  BANK_STATEMENT = 'BANK_STATEMENT',
  CREDIT_OR_DEBIT_CARD = 'CREDIT_OR_DEBIT_CARD',
  DRIVING_LICENSE = 'DRIVING_LICENSE',
  EMPLOYER_LETTER = 'EMPLOYER_LETTER',
  ID_CARD = 'ID_CARD',
  INSURANCE_AGREEMENT = 'INSURANCE_AGREEMENT',
  PASSPORT = 'PASSPORT',
  RENT_AGREEMENT = 'RENT_AGREEMENT',
  TAX_BILL = 'TAX_BILL',
  UTILITY_BILL = 'UTILITY_BILL',
}

export enum statuses {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
}

export const documentsCategoriesLabels: Record<documentsCategories, string> = {
  [documentsCategories.DOCUMENT_VERIFICATION]: 'FILES.CATEGORY.DOCUMENT_VERIFICATION',
  [documentsCategories.ADDRESS_VERIFICATION]: 'FILES.CATEGORY.ADDRESS_VERIFICATION',
  [documentsCategories.OTHER]: 'FILES.CATEGORY.OTHER',
};

export const documentsTypeLabels: Record<documentsType, string> = {
  [documentsType.BANK_STATEMENT]: 'FILES.DOCUMENTS_TYPE.BANK_STATEMENT',
  [documentsType.CREDIT_OR_DEBIT_CARD]: 'FILES.DOCUMENTS_TYPE.CREDIT_OR_DEBIT_CARD',
  [documentsType.DRIVING_LICENSE]: 'FILES.DOCUMENTS_TYPE.DRIVING_LICENSE',
  [documentsType.EMPLOYER_LETTER]: 'FILES.DOCUMENTS_TYPE.EMPLOYER_LETTER',
  [documentsType.ID_CARD]: 'FILES.DOCUMENTS_TYPE.ID_CARD',
  [documentsType.INSURANCE_AGREEMENT]: 'FILES.DOCUMENTS_TYPE.INSURANCE_AGREEMENT',
  [documentsType.PASSPORT]: 'FILES.DOCUMENTS_TYPE.PASSPORT',
  [documentsType.RENT_AGREEMENT]: 'FILES.DOCUMENTS_TYPE.RENT_AGREEMENT',
  [documentsType.TAX_BILL]: 'FILES.DOCUMENTS_TYPE.TAX_BILL',
  [documentsType.UTILITY_BILL]: 'FILES.DOCUMENTS_TYPE.UTILITY_BILL',
};

export const statusesLabels: Record<statuses, string> = {
  [statuses.APPROVED]: 'FILES.STATUSES.APPROVED',
  [statuses.REJECTED]: 'FILES.STATUSES.REJECTED',
  [statuses.PENDING]: 'FILES.STATUSES.PENDING',
};
