export enum branchTypes {
  OFFICE = 'OFFICE',
  DESK = 'DESK',
  TEAM = 'TEAM',
  COMPANY = 'COMPANY',
  BRAND = 'BRAND',
}

export enum userTypes {
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  BRAND_ADMIN = 'BRAND_ADMIN',
  SALES_HOD = 'SALES_HOD',
  RETENTION_HOD = 'RETENTION_HOD',
  SUPPORT_HOD = 'SUPPORT_HOD',
  PSP_HOD = 'PSP_HOD',
  SALES_MANAGER = 'SALES_MANAGER',
  RETENTION_MANAGER = 'RETENTION_MANAGER',
  SUPPORT_MANAGER = 'SUPPORT_MANAGER',
  PSP_MANAGER = 'PSP_MANAGER',
  BO_MANAGER = 'BO_MANAGER',
  COMPLIANCE_MANAGER = 'COMPLIANCE_MANAGER',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  DEALING_MANAGER = 'DEALING_MANAGER',
  SALES_LEAD = 'SALES_LEAD',
  RETENTION_LEAD = 'RETENTION_LEAD',
  SUPPORT_LEAD = 'SUPPORT_LEAD',
  SALES_AGENT = 'SALES_AGENT',
  RETENTION_AGENT = 'RETENTION_AGENT',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  CUSTOMER = 'CUSTOMER',
  LEAD_CUSTOMER = 'LEAD_CUSTOMER',
  AFFILIATE_PARTNER = 'AFFILIATE_PARTNER',
  AFFILIATE_MANAGER = 'AFFILIATE_MANAGER',
}

export enum deskTypes {
  RETENTION = 'RETENTION',
  SALES = 'SALES',
}

export const userTypeLabels: Record<userTypes, string> = {
  [userTypes.COMPANY_ADMIN]: 'CONSTANTS.HIERARCHY.USER_TYPES.COMPANY_ADMIN',
  [userTypes.BRAND_ADMIN]: 'CONSTANTS.HIERARCHY.USER_TYPES.BRAND_ADMIN',
  [userTypes.SALES_HOD]: 'CONSTANTS.HIERARCHY.USER_TYPES.SALES_HOD',
  [userTypes.RETENTION_HOD]: 'CONSTANTS.HIERARCHY.USER_TYPES.RETENTION_HOD',
  [userTypes.SUPPORT_HOD]: 'CONSTANTS.HIERARCHY.USER_TYPES.SUPPORT_HOD',
  [userTypes.PSP_HOD]: 'CONSTANTS.HIERARCHY.USER_TYPES.PSP_HOD',
  [userTypes.SALES_MANAGER]: 'CONSTANTS.HIERARCHY.USER_TYPES.SALES_MANAGER',
  [userTypes.RETENTION_MANAGER]: 'CONSTANTS.HIERARCHY.USER_TYPES.RETENTION_MANAGER',
  [userTypes.SUPPORT_MANAGER]: 'CONSTANTS.HIERARCHY.USER_TYPES.SUPPORT_MANAGER',
  [userTypes.PSP_MANAGER]: 'CONSTANTS.HIERARCHY.USER_TYPES.PSP_MANAGER',
  [userTypes.BO_MANAGER]: 'CONSTANTS.HIERARCHY.USER_TYPES.BO_MANAGER',
  [userTypes.COMPLIANCE_MANAGER]: 'CONSTANTS.HIERARCHY.USER_TYPES.COMPLIANCE_MANAGER',
  [userTypes.OPERATIONS_MANAGER]: 'CONSTANTS.HIERARCHY.USER_TYPES.OPERATIONS_MANAGER',
  [userTypes.DEALING_MANAGER]: 'CONSTANTS.HIERARCHY.USER_TYPES.DEALING_MANAGER',
  [userTypes.SALES_LEAD]: 'CONSTANTS.HIERARCHY.USER_TYPES.SALES_LEAD',
  [userTypes.RETENTION_LEAD]: 'CONSTANTS.HIERARCHY.USER_TYPES.RETENTION_LEAD',
  [userTypes.SUPPORT_LEAD]: 'CONSTANTS.HIERARCHY.USER_TYPES.SUPPORT_LEAD',
  [userTypes.SALES_AGENT]: 'CONSTANTS.HIERARCHY.USER_TYPES.SALES_AGENT',
  [userTypes.RETENTION_AGENT]: 'CONSTANTS.HIERARCHY.USER_TYPES.RETENTION_AGENT',
  [userTypes.SUPPORT_AGENT]: 'CONSTANTS.HIERARCHY.USER_TYPES.SUPPORT_AGENT',
  [userTypes.CUSTOMER]: 'CONSTANTS.HIERARCHY.USER_TYPES.CUSTOMER',
  [userTypes.LEAD_CUSTOMER]: 'CONSTANTS.HIERARCHY.USER_TYPES.LEAD_CUSTOMER',
  [userTypes.AFFILIATE_PARTNER]: 'CONSTANTS.HIERARCHY.USER_TYPES.AFFILIATE_PARTNER',
  [userTypes.AFFILIATE_MANAGER]: 'CONSTANTS.HIERARCHY.USER_TYPES.AFFILIATE_MANAGER',
};

/**
 * Check if userType is sales
 *
 * @param userType
 *
 * @return {boolean}
 */
export const isSales = (userType: userTypes) => [
  userTypes.SALES_AGENT,
  userTypes.SALES_LEAD,
  userTypes.SALES_MANAGER,
  userTypes.SALES_HOD,
].includes(userType);

/**
 * Check if userType is retention
 *
 * @param userType
 *
 * @return {boolean}
 */
export const isRetention = (userType: userTypes) => [
  userTypes.RETENTION_AGENT,
  userTypes.RETENTION_LEAD,
  userTypes.RETENTION_MANAGER,
  userTypes.RETENTION_HOD,
].includes(userType);

/**
 * Check if userType is lead
 *
 * @param userType
 *
 * @return {boolean}
 */
export const isLead = (userType: userTypes) => userType === userTypes.LEAD_CUSTOMER;
