import I18n from 'i18n-js';

export const attributeLabels = {
  name: I18n.t('CLIENT_PROFILE.ACCOUNTS.MODAL_CREATE.NAME_LABEL'),
  accountType: I18n.t('CLIENT_PROFILE.ACCOUNTS.MODAL_CREATE.ACCOUNT_TYPE_LABEL'),
  platformType: I18n.t('CLIENT_PROFILE.ACCOUNTS.MODAL_CREATE.PLATFORM_TYPE_LABEL'),
  amount: I18n.t('CLIENT_PROFILE.ACCOUNTS.MODAL_CREATE.AMOUNT_LABEL'),
  currency: I18n.t('CLIENT_PROFILE.ACCOUNTS.MODAL_CREATE.CURRENCY_LABEL'),
  password: I18n.t('CLIENT_PROFILE.ACCOUNTS.MODAL_CREATE.PASSWORD_LABEL'),
};

export const amounts = [100, 500, 1000, 5000, 10000, 50000, 100000];
