query DistributionRuleQuery($uuid: String!) {
  distributionRule (uuid: $uuid) {
    _id
    uuid
    name
    order
    status
    statusChangedAt
    createdAt
    updatedAt
    countries
    languages
    firstTimeDeposit
    salesStatuses
    targetSalesStatus
    registrationPeriodInHours
    registrationDateRange {
      from
      to
    }
    lastNotePeriodInHours
    lastNoteDateRange {
      from
      to
    }
    executionType
    executionPeriodInHours
    latestMigration {
      startDate
    }
    sourceBrandConfigs {
      brand
      affiliateUuids
      distributionUnit {
        quantity
        baseUnit
      }
      sortType
      desks
      teams
    }
    targetBrandConfigs {
      brand
      copyAffiliateSource
      distributionUnit {
        quantity
        baseUnit
      }
      affiliateUuid
      operator
      operatorEntity {
        uuid
        fullName
      }
    }
  }
}
