mutation UpdateConfigurationDepositMutation ($playerUUID: String!, $enabled: Boolean!) {
  profile {
    updateConfigurationDeposit(playerUUID: $playerUUID, enabled: $enabled) {
      depositEnabled
    }
  }
}
