query PartnerQuery(
  $uuid: String!
) {
  partner(
    uuid: $uuid
  ) {
    _id
    uuid
    firstName
    lastName
    fullName
    email
    externalAffiliateId
    public
    phone
    country
    status
    statusChangeDate
    statusChangeAuthor
    createdBy
    createdAt
    cdeAffiliate
    permission {
      allowedIpAddresses
      forbiddenCountries
      restrictedSources
      restrictedReferrals
      showSalesStatus
      showFTDAmount
      showKycStatus
      showNotes
      cumulativeDeposit
      showAutologinUrl
      minFtdDeposit
    }
    schedule {
      configId
      activated
      countrySpreads {
        country
        limit
      },
      day
      totalLimit
      workingHoursFrom
      workingHoursTo
    }
    authorities {
      brand
      department
      id
      role
    }
  }
}
