query AccountQuery($identifier: String!) {
  tradingEngine {
    account(identifier: $identifier) {
      uuid
      name
      login
      group
      credit
      balance
      accountType
      statistic {
        freeMargin
      }
    }
  }
}
