import I18n from '../../../../utils/fake-i18n';

const attributeLabels = {
  lifeTime: I18n.t('CAMPAIGNS.REWARDS.FREE_SPIN.LIFE_TIME'),
  addFreeSpin: I18n.t('CAMPAIGNS.REWARDS.FREE_SPIN.ADD_FREE_SPIN'),
  denomination: I18n.t('CAMPAIGNS.FREE_SPIN.DENOMINATION'),
  coins: I18n.t('CAMPAIGNS.FREE_SPIN.COINS'),
  template: I18n.t('CAMPAIGNS.REWARDS.FREE_SPIN.TEMPLATE'),
  status: I18n.t('CAMPAIGNS.REWARDS.FREE_SPIN.STATUS'),
  providerId: I18n.t('CAMPAIGNS.FREE_SPIN.PROVIDER'),
  aggregatorId: I18n.t('CAMPAIGNS.FREE_SPIN.AGGREGATOR'),
  gameId: I18n.t('CAMPAIGNS.FREE_SPIN.GAME'),
  gameType: I18n.t('CAMPAIGNS.FREE_SPIN.GAME_TYPE'),
  name: I18n.t('CAMPAIGNS.FREE_SPIN.NAME'),
  freeSpins: I18n.t('CAMPAIGNS.FREE_SPIN.FREE_SPINS'),
  freeSpinReward: I18n.t('CAMPAIGNS.FREE_SPIN.FREE_SPIN_REWARD'),
  betPerLine: I18n.t('CAMPAIGNS.FREE_SPIN.BET_PER_LINE'),
  prize: I18n.t('CAMPAIGNS.FREE_SPIN.PRIZE'),
  wagering: I18n.t('CAMPAIGNS.FREE_SPIN.WAGERING'),
  capping: I18n.t('CAMPAIGNS.FREE_SPIN.CAPPING'),
  moneyPriority: I18n.t('CAMPAIGNS.FREE_SPIN.MONEY_PRIORITY'),
  spinValue: I18n.t('CAMPAIGNS.FREE_SPIN.SPIN_VALUE'),
  totalValue: I18n.t('CAMPAIGNS.FREE_SPIN.TOTAL_VALUE'),
  linesPerSpin: I18n.t('CAMPAIGNS.FREE_SPIN.LINES_PER_SPIN'),
  betLevel: I18n.t('CAMPAIGNS.FREE_SPIN.BET_LEVEL'),
  coinSize: I18n.t('CAMPAIGNS.FREE_SPIN.COIN_SIZE'),
  freeSpinLifeTime: I18n.t('CAMPAIGNS.FREE_SPIN.FREE_SPIN_LIFE_TIME'),
  pageCode: I18n.t('CAMPAIGNS.FREE_SPIN.PAGE_CODE'),
  comment: I18n.t('CAMPAIGNS.FREE_SPIN.COMMENT'),
  betMultiplier: I18n.t('CAMPAIGNS.FREE_SPIN.BET_MULTIPLIER'),
  rhfpBet: I18n.t('CAMPAIGNS.FREE_SPIN.RHFP_BET'),
  nearestCost: I18n.t('CAMPAIGNS.FREE_SPIN.NEAREST_COST'),
  displayLine1: I18n.t('CAMPAIGNS.FREE_SPIN.DISPLAY_LINE1'),
  displayLine2: I18n.t('CAMPAIGNS.FREE_SPIN.DISPLAY_LINE2'),
  bonusTemplate: I18n.t('CAMPAIGNS.FREE_SPIN.BONUS_TEMPLATE'),
  claimable: I18n.t('COMMON.CLAIMABLE'),
};

const attributePlaceholders = {
  days: I18n.t('CAMPAIGNS.FREE_SPIN.PLACEHOLDERS.DAYS'),
};

export {
  attributeLabels,
  attributePlaceholders,
};
