export const attributeLabels = {
  country: 'PLAYER_PROFILE.PROFILE.ADDRESS.LABEL.COUNTRY',
  city: 'PLAYER_PROFILE.PROFILE.ADDRESS.LABEL.CITY',
  postCode: 'PLAYER_PROFILE.PROFILE.ADDRESS.LABEL.POST_CODE',
  address: 'PLAYER_PROFILE.PROFILE.ADDRESS.LABEL.FULL_ADDR',
  poBox: 'PLAYER_PROFILE.PROFILE.ADDRESS.LABEL.PO_BOX',
};
