export const types = [{
  value: 'BUY_LIMIT',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.BUY_LIMIT',
}, {
  value: 'SELL_LIMIT',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.SELL_LIMIT',
}, {
  value: 'BUY_STOP',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.BUY_STOP',
}, {
  value: 'SELL_STOP',
  label: 'TRADING_ENGINE.ORDERS.FILTER_FORM.TYPES.SELL_STOP',
}];
