const filterFormAttributeLabels = {
  searchBy: 'OPERATOR_PROFILE.FEED.FILTER_FORM.SEARCH_BY_LABEL',
  actionType: 'OPERATOR_PROFILE.FEED.FILTER_FORM.SEARCH_BY_LABEL',
  creationDateFrom: 'OPERATOR_PROFILE.FEED.FILTER_FORM.SEARCH_BY_LABEL',
  creationDateTo: 'OPERATOR_PROFILE.FEED.FILTER_FORM.SEARCH_BY_LABEL',
};

export { filterFormAttributeLabels };
