const accountTypes = {
  LIVE: 'TRADING_ACCOUNTS.FORM.ACCOUNT_TYPE.LIVE',
  DEMO: 'TRADING_ACCOUNTS.FORM.ACCOUNT_TYPE.DEMO',
};

const accountStatuses = {
  0: 'TRADING_ACCOUNTS.FORM.STATUS.NOT_ARCHIVED',
  1: 'TRADING_ACCOUNTS.FORM.STATUS.ARCHIVED',
};

const affiliateTypes = {
  AFFILIATE: 'TRADING_ACCOUNTS.FORM.AFFILIATE_TYPE.AFFILIATE',
  IB: 'TRADING_ACCOUNTS.FORM.AFFILIATE_TYPE.IB',
  DIRECT: 'TRADING_ACCOUNTS.FORM.AFFILIATE_TYPE.DIRECT',
};

export {
  accountTypes,
  accountStatuses,
  affiliateTypes,
};
