import I18n from '../../../../utils/fake-i18n';

export default {
  name: I18n.t('HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.RULE_NAME'),
  country: I18n.t('HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.COUNTRY'),
  language: I18n.t('HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.LANGUAGE'),
  priority: I18n.t('HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.PRIORITY'),
  type: I18n.t('HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.TYPE'),
};
