export default {
  name: 'HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.RULE_NAME',
  country: 'HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.COUNTRY',
  language: 'HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.LANGUAGE',
  priority: 'HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.PRIORITY',
  type: 'HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.TYPE',
  depositCount: 'HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.DEPOSIT_COUNT',
  amount: 'HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.AMOUNT',
  distribution: 'HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.DISTRIBUTION',
  partner: 'HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.PARTNER',
  source: 'HIERARCHY.PROFILE_RULE_TAB.MODAL.LABELS.SOURCE',
};
