mutation NoteCreateMutation(
  $playerUUID: String!
  $content: String!
  $targetUUID: String!
  $targetType: String!
) {
  note {
    add(
      playerUUID: $playerUUID
      content: $content
      targetUUID: $targetUUID
      targetType: $targetType
      pinned: false
    )
  }
}
