query AccountQuery($identifier: String!) {
  tradingEngine {
    account(identifier: $identifier) {
      uuid
      name
      login
      group
      currency
      credit
      balance
      accountType
      leverage
      enable
    }
  }
}
