const attributeLabels = {
  keyword: 'OPERATORS.LIST.FILTER_FORM.LABEL.KEYWORD',
  country: 'OPERATORS.LIST.FILTER_FORM.LABEL.COUNTRY',
  status: 'OPERATORS.LIST.FILTER_FORM.LABEL.STATUS',
  department: 'OPERATORS.LIST.FILTER_FORM.LABEL.DEPARTMENT',
  role: 'OPERATORS.LIST.FILTER_FORM.LABEL.ROLE',
  registrationDateFrom: 'OPERATORS.LIST.FILTER_FORM.LABEL.REGISTRATION_DATE_FROM',
  registrationDateTo: 'OPERATORS.LIST.FILTER_FORM.LABEL.REGISTRATION_DATE_TO',
};

export {
  attributeLabels,
};

export default attributeLabels;
