#import "apollo/fragments/Payment"

query PaymentsQuery($args: PaymentSearch__Input) {
  payments(args: $args) {
    page
    number
    totalElements
    size
    last
    content {
      ...PaymentFragment
    }
  }
}
