import I18n from '../../../../../../utils/fake-i18n';

const attributeLabels = {
  campaignName: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.CAMPAIGN_NAME'),
  campaignPriority: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.PRIORITY'),
  moneyTypePriority: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.MONEY_TYPE_PRIORITY'),
  targetType: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.TARGET_TYPE'),
  currency: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.CURRENCY'),
  startDate: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.START_DATE'),
  endDate: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.END_DATE'),
  capping: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.CAPPING'),
  'capping.value': I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.CAPPING'),
  wagerWinMultiplier: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.MULTIPLIER'),
  bonusLifetime: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.BONUS_LIFE_TIME'),
  campaignType: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.CAMPAIGN_TYPE'),
  campaignRatio: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.CAMPAIGN_RATIO'),
  'campaignRatio.value': I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.CAMPAIGN_RATIO'),
  conversionPrize: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.CONVERSION_PRIZE'),
  'conversionPrize.value': I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.CONVERSION_PRIZE'),
  optIn: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.OPT_IN'),
  minAmount: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.MIN_AMOUNT'),
  maxAmount: I18n.t('BONUS_CAMPAIGNS.SETTINGS.LABEL.MAX_AMOUNT'),
  addFulfillment: I18n.t('BONUS_CAMPAIGNS.FULFILLMENTS.ADD_FULFILLMENT'),
  registrationFulfillment: I18n.t('BONUS_CAMPAIGNS.FULFILLMENTS.REGISTRATION_FULFILLMENT'),
  depositFulfillment: I18n.t('BONUS_CAMPAIGNS.FULFILLMENTS.DEPOSIT_FULFILLMENT'),
  wageringFulfillment: I18n.t('BONUS_CAMPAIGNS.FULFILLMENTS.WAGERING_FULFILLMENT'),
  loginFulfillment: I18n.t('BONUS_CAMPAIGNS.FULFILLMENTS.LOGIN_FULFILLMENT'),
  campaignFulfillment: I18n.t('BONUS_CAMPAIGNS.FULFILLMENTS.CAMPAIGN_FULFILLMENT'),
  emailVerificationFulfillment: I18n.t('BONUS_CAMPAIGNS.FULFILLMENTS.EMAIL_VERIFICATION_FULFILLMENT'),
  phoneVerificationFulfillment: I18n.t('BONUS_CAMPAIGNS.FULFILLMENTS.PHONE_VERIFICATION_FULFILLMENT'),
  addReward: I18n.t('BONUS_CAMPAIGNS.REWARDS.ADD_REWARD'),
};

export default attributeLabels;
