query PartnersQuery(
  $page: Page__Input
  $searchBy: String
  $country: String
  $status: String
  $registrationDateFrom: String
  $registrationDateTo: String
) {
  partners (
    page: $page
    searchBy: $searchBy
    country: $country
    status: $status
    registrationDateFrom: $registrationDateFrom
    registrationDateTo: $registrationDateTo
  ) {
    page
    number
    totalElements
    size
    last
    content {
      _id
      uuid
      fullName
      createdAt
      externalAffiliateId
      status
      statusChangeDate
      country
    }
  }
}
